name: 'Netlify Deploy'
description: 'Github action for deploying to Netlify'
author: 'Joshua Navi'
inputs:
  dir:
    description: 'The directory to publish to the site'
    required: true
  message:
    description: 'The message that will show up for this deploy in Netlify'
    required: true
  isProd:
    description: 'Whether or nor to deploy to the production site (if omitted the deploy will be a preview deploy)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
