name: 'Deploy to Netlify'
description: 'Github action for deploying to Netlify'
author: 'Joshua Navi'
inputs:
  dir:
    description: 'The directory to publish to the site'
    required: true
  message:
    description: 'The message that will show up for this deploy in Netlify'
    required: true
  isProd:
    description: 'Whether or not to deploy to the production site (if omitted the deploy will be a preview deploy)'
    required: true
  alias:
    description: 'The deploy alias to be used for the site deploy'
    required: false
  functions-dir:
    description: 'The directory where functions will be located for publishing'
    required: false
outputs:
  deploy-id:
    description: The id (hash) of the deploy in Netlify
  deploy-url:
    description: The url that the site was deployed to
  deploy-json:
    description: The full json of the deploy object
runs:
  using: 'node16'
  main: 'dist/index.js'
